apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblioteca-front-deployment
spec:
  selector:
    matchLabels:
      app: biblioteca-front
  replicas: 2
  template:
    metadata:
      labels:
        app: biblioteca-front
    spec:
      containers:
        - name: biblioteca-front
          image: biblioteca-front:0.0.1
          ports:
            - containerPort: 80
              name: bibliotecafport