apiVersion: v1
kind: Service
metadata:
  name: biblioteca-front-service
  labels:
    app: biblioteca-front
spec:
  ports:
    - name: biblioteca-front
      port: 81          # Cambiado de 80 a 81
      targetPort: 81    # Asegúrate de incluir esto
      nodePort: 30222
  type: NodePort
  selector: 
    app: biblioteca-front