apiVersion: v1
kind: Service
metadata:
  name: biblioteca-front-service
  labels:
    app: biblioteca-front
spec:
  ports:
    - name: biblioteca-front
      port: 80
      nodePort: 30222
  type: NodePort
  selector:
    app: biblioteca-front