# Usar la versión de Node.js 18.17.1-alpine
FROM node:18.17.1-alpine

# Crear un directorio de trabajo
WORKDIR /usr/src/app

# Copiar los archivos package.json y package-lock.json al directorio de trabajo
COPY package.json package-lock.json ./

# Instalar las dependencias
RUN npm install --force

# Copiar todo el directorio del proyecto al contenedor
COPY . .

# Exponer el puerto 3000
EXPOSE 3000

# Ejecutar directamente la aplicación sin esperar a MySQL
CMD ["node", "index.js"]
